// modules
import Head from 'next/head';
import { observer } from 'mobx-react-lite';

// components
import { Header, Content } from '../components/layouts';

// styles
import styles from '../styles/Home.module.css';

const Home = observer(() => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Book finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
    </div>
  );
});

export default Home;
